name: Deploy Portainer to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0'

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          cat <<EOF > $HOME/.kube/config
          apiVersion: v1
          kind: Config
          clusters:
          - cluster:
              certificate-authority-data: ${{ secrets.KUBE_CA }}
              server: https://74bf251611ae.ngrok-free.app
            name: minikube
          contexts:
          - context:
              cluster: minikube
              user: github
            name: minikube
          current-context: minikube
          users:
          - name: github
            user:
              token: ${{ secrets.KUBE_TOKEN }}
          EOF

      - name: Deploy Portainer
        run: |
          kubectl apply -f k8s/portainer.yaml
